# Generated by Django 2.1.2 on 2018-12-04 12:35

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('hash', models.CharField(max_length=256)),
                ('actor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('category', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('source', models.CharField(max_length=1024)),
                ('verb', models.CharField(max_length=256)),
                ('object', models.CharField(max_length=256)),
                ('handler', models.CharField(max_length=256)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('description', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
