# Generated by Django 2.1.2 on 2018-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='object',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='verb',
        ),
        migrations.AlterField(
            model_name='fact',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
