# Generated by Django 2.1.2 on 2018-12-12 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20181212_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='actor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
